org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.11
minecraft_version_range=[1.21.11,1.22)
neo_version=21.11.42
loader_version_range=[1,)

java_version=21

mod_version=1.0.0
mod_group_id=com.arthou.tpa
archives_base_name=arthous-tpa-neoforge-12111
mod_id=tpa
mod_name=Arthou's TPA
mod_license=MIT
mod_authors=arthou
mod_description=Arthou's TPA for NeoForge with requests, homes, warps, spawn, back, RTP and logout teleport.
